site_name: Interactive Visual Framework 2 
site_description: Documentation for the Ivf2 C++ graphics library
site_author: Jonas Lindemann

repo_url: https://github.com/jonaslindemann/ivf2
repo_name: GitHub

theme:
  name: material
  palette: 

    - scheme: slate
      accent: yellow
      primary: yellow
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.code.annotate


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.snippets:
      base_path: ../
  - admonition
  - toc:
      permalink: true
  - attr_list

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Basic Concepts: getting_started/basic_concepts.md
    - Your first Application: getting_started/your_first_app.md
  - Core:
    - Nodes: core/nodes.md
    - Materials and Textures: core/materials_and_textures.md
    - Lighting: core/lighting.md
  - Primitives:
    - Basic Primitives: primitives/basic_primitives.md
    - Complex Primitives: primitives/complex_primitives.md
  - UI:
    - UI Windows: ui/ui_windows.md
    - Scene Window: ui/scene_window.md
  - Examples:
    - Primitive Examples: examples/primitives_examples.md
    - Texture Examples: examples/texture_examples.md
    - Animation Examples: examples/animation_examples.md
    - Asset Examples: examples/asset_examples.md
    - Deformer Examples: examples/deformer_examples.md
    - Lighting Examples: examples/lighting_examples.md
    - Interaction Examples: examples/interaction_examples.md
    - Effects Examples: examples/effects_examples.md
    - UI Examples: examples/ui_examples.md

  - API Reference:
    - Overview: api/index.md

plugins:
  - search
  - minify:
      minify_html: true

